"""add users and weather tables.

Revision ID: 6c24ef5ad261
Revises: 2b7380507a71
Create Date: 2026-04-27 13:12:09.730807

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6c24ef5ad261"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column("weather", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "weather",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weather",
        "feels_like",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weather",
        "humidity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "weather", "time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("weather", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_weather_id"), table_name="weather")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_weather_id"), "weather", ["id"], unique=False)
    op.alter_column("weather", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "weather", "time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "weather",
        "humidity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weather",
        "feels_like",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "weather",
        "temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("weather", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "books",
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "book_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "customer_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("book_id", name=op.f("books_pkey")),
    )
    # ### end Alembic commands ###
