"""initial.

Revision ID: 357c8c6f061a
Revises: 6c24ef5ad261
Create Date: 2026-04-27 15:09:28.689153

"""



# revision identifiers, used by Alembic.
revision = "357c8c6f061a"
down_revision = "6c24ef5ad261"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
